"""
AEO Appium Orchestrator — v1.0
--------------------------------
Self-contained: generates prompts, distributes to devices, runs in TRUE parallel via threading.
Device pool is fully dynamic — read from active_devices.json (generated by setup_devices.py)
or discovered live from 'adb devices'. No hardcoded serials or device counts.

Usage:
  python main.py                  # run daily AEO sessions
  python main.py --audit          # run weekly ranking audit
  python main.py --status         # show today's status
  python main.py --reset          # reset today's rotation (testing)
"""

import json
import os
import sys
import random
import argparse
import subprocess
import threading
from datetime import datetime, date

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from agents.prompt_generator import generate_session_prompts
from agents.ranking_auditor import generate_ranking_prompt
from session_runner import run_parallel


# ── Paths ─────────────────────────────────────────────────────────────────────

BASE_DIR             = os.path.dirname(os.path.abspath(__file__))
CLIENTS_FILE         = os.path.join(BASE_DIR, "clients.json")
ROTATION_FILE        = os.path.join(BASE_DIR, "device_rotation.json")
LOG_FILE             = os.path.join(BASE_DIR, "sessions_log.json")
ACTIVE_DEVICES_FILE  = os.path.join(BASE_DIR, "active_devices.json")

BASE_APPIUM_PORT = 4723
PLATFORMS        = ["Gemini", "ChatGPT", "Perplexity"]


# ── Thread locks for file writes ───────────────────────────────────────────────

_rotation_lock = threading.Lock()
_log_lock      = threading.Lock()


# ── Device Pool ───────────────────────────────────────────────────────────────

def _discover_from_adb():
    """
    Discover all connected devices from 'adb devices'.
    Returns dict: {"device-001": {"serial": ..., "port": 4723}, ...}
    Labels and ports are assigned sequentially by sorted transport name.
    """
    try:
        result = subprocess.run(
            ["adb", "devices"], capture_output=True, text=True, timeout=10
        )
    except Exception:
        return {}

    transports = []
    for line in result.stdout.splitlines()[1:]:
        parts = line.strip().split()
        if len(parts) >= 2 and parts[1] == "device":
            transports.append(parts[0])

    pool = {}
    for idx, full_transport in enumerate(sorted(transports)):
        label        = f"device-{idx + 1:03d}"
        short_serial = _short_serial(full_transport)
        pool[label]  = {"serial": short_serial, "port": BASE_APPIUM_PORT + idx}

    return pool


def _short_serial(full_transport):
    """Extract stable short serial from full ADB transport name."""
    if full_transport.startswith("adb-") and "._adb-tls-connect" in full_transport:
        inner = full_transport[4:]
        inner = inner.split("._adb-tls-connect")[0]
        return inner.rsplit("-", 1)[0]
    return full_transport


def _get_connected_serials():
    """Return set of short serials currently connected via ADB."""
    try:
        result = subprocess.run(
            ["adb", "devices"], capture_output=True, text=True, timeout=10
        )
    except Exception:
        return set()

    connected = set()
    for line in result.stdout.splitlines()[1:]:
        parts = line.strip().split()
        if len(parts) >= 2 and parts[1] == "device":
            connected.add(_short_serial(parts[0]))
    return connected


def _load_device_pool():
    """
    Load device pool from active_devices.json if present,
    otherwise discover live from adb devices.

    Only includes devices that are actually connected via ADB right now.
    """
    if os.path.exists(ACTIVE_DEVICES_FILE):
        try:
            with open(ACTIVE_DEVICES_FILE, "r") as f:
                active = json.load(f)
            if active:
                connected = _get_connected_serials()
                pool = {}
                for label, info in active.items():
                    if info["serial"] in connected:
                        pool[label] = info
                    else:
                        print(f"  {label} ({info['serial']}) — offline, skipping")
                print(f"Using active_devices.json — {len(pool)}/{len(active)} device(s) online")
                return pool
        except Exception:
            pass

    print("No active_devices.json — discovering from adb devices...")
    pool = _discover_from_adb()
    if pool:
        print(f"  Found {len(pool)} connected device(s)")
    else:
        print("  No devices found. Connect devices and run: python setup_devices.py --assign")
    return pool


DEVICE_POOL = _load_device_pool()


# ── Serial Resolver ────────────────────────────────────────────────────────────

def get_adb_transport_map():
    """
    Map short device serial → full ADB transport name.
    e.g. "1490455613010287" → "adb-1490455613010287-g9bnc8._adb-tls-connect._tcp"
    """
    try:
        result = subprocess.run(
            ["adb", "devices"], capture_output=True, text=True, timeout=10
        )
    except Exception:
        return {}

    transport_map = {}
    for line in result.stdout.splitlines()[1:]:
        parts = line.strip().split()
        if len(parts) >= 2 and parts[1] == "device":
            transport = parts[0]
            short     = _short_serial(transport)
            transport_map[short] = transport
    return transport_map


def resolve_serial(short_serial, transport_map):
    """Return full ADB transport for a short serial, or original if not found."""
    resolved = transport_map.get(short_serial, short_serial)
    if resolved == short_serial and short_serial not in transport_map.values():
        print(f"  Could not resolve serial '{short_serial}' — device may be offline")
    return resolved


# ── Data Loaders ──────────────────────────────────────────────────────────────

def load_clients():
    with open(CLIENTS_FILE, "r") as f:
        return json.load(f)


def load_rotation():
    try:
        with open(ROTATION_FILE, "r") as f:
            return json.load(f)
    except Exception:
        return {}


def save_rotation(data):
    with open(ROTATION_FILE, "w") as f:
        json.dump(data, f, indent=2)


# ── Rotation Logic ────────────────────────────────────────────────────────────

def get_today_rotation():
    today    = str(date.today())
    rotation = load_rotation()
    if today not in rotation:
        rotation[today] = {d: {} for d in DEVICE_POOL}
        save_rotation(rotation)
    return rotation[today]


def is_keyword_done_today(client_id, keyword):
    today_rot = get_today_rotation()
    rot_key   = f"{client_id}:{keyword}"
    return any(rot_key in today_rot.get(d, {}) for d in DEVICE_POOL)


def has_device_done_client_today(device_id, client_id):
    """Check if this device already ran this client today (1 device per client per day)."""
    today_rot = get_today_rotation()
    for rot_key in today_rot.get(device_id, {}):
        if rot_key.startswith(f"{client_id}:"):
            return True
    return False


def get_device_client_count_today(device_id):
    """How many unique clients this device has served today."""
    today_rot = get_today_rotation()
    client_ids = set()
    for rot_key in today_rot.get(device_id, {}):
        cid = rot_key.split(":")[0]
        client_ids.add(cid)
    return len(client_ids)


def mark_device_used(device_id, client_id, keyword, platform):
    today   = str(date.today())
    rot_key = f"{client_id}:{keyword}"
    with _rotation_lock:
        rotation = load_rotation()
        if today not in rotation:
            rotation[today] = {d: {} for d in DEVICE_POOL}
        rotation[today].setdefault(device_id, {})[rot_key] = {
            "client_id": client_id,
            "keyword":   keyword,
            "platform":  platform,
            "status":    "started",
            "timestamp": datetime.utcnow().isoformat() + "Z",
        }
        save_rotation(rotation)


def update_status(device_id, client_id, keyword, status):
    today   = str(date.today())
    rot_key = f"{client_id}:{keyword}"
    with _rotation_lock:
        try:
            rotation = load_rotation()
            rotation[today][device_id][rot_key]["status"]       = status
            rotation[today][device_id][rot_key]["completed_at"] = datetime.utcnow().isoformat() + "Z"
            save_rotation(rotation)
        except Exception:
            pass


# ── Logging ───────────────────────────────────────────────────────────────────

def log_session(client, keyword, prompt, follow_up, device_id, status,
                proxy_info=None, platform_results=None):
    """
    Log one session entry. 1 session = 1 keyword + 1 proxy + all platforms.
    """
    entry = {
        "timestamp":     datetime.utcnow().isoformat() + "Z",
        "date":          str(date.today()),
        "client_id":     client["id"],
        "client_name":   client["biz_name"],
        "city":          client["city"],
        "keyword":       keyword,
        "prompt":        prompt,
        "follow_up":     follow_up,
        "has_follow_up": follow_up is not None,
        "device_id":     device_id,
        "status":        status,
        "runner":        "appium",
    }

    if proxy_info:
        entry["proxy"] = {
            "status":     proxy_info.get("status"),
            "username":   proxy_info.get("username"),
            "proxy_host": proxy_info.get("proxy_host"),
            "proxy_port": proxy_info.get("proxy_port"),
        }

    if platform_results:
        entry["platforms"] = {}
        for pr in platform_results:
            plat = pr.get("platform", "unknown")
            entry["platforms"][plat] = {
                "status": "success" if pr.get("success") else "error",
                "steps":  pr.get("steps", []),
            }

    with _log_lock:
        try:
            with open(LOG_FILE, "r") as f:
                logs = json.load(f)
        except Exception:
            logs = []
        logs.append(entry)
        with open(LOG_FILE, "w") as f:
            json.dump(logs, f, indent=2)


# ── Session Planning ──────────────────────────────────────────────────────────

def plan_sessions(max_clients=None):
    """
    Distribute keywords across devices respecting rotation rules:
      - 1 device + 1 client = 1 keyword per day (device can't repeat same client)
      - Each keyword runs on exactly 1 device per day (no duplicates)
      - A device CAN serve multiple clients (1 keyword each)
      - Round-robin: spread clients across devices evenly

    Example with 2 devices, 3 clients (5 kw each):
      Device 1: C1-KW1, C2-KW1, C3-KW1 (3 sessions, sequential)
      Device 2: C1-KW2, C2-KW2, C3-KW2 (3 sessions, sequential)
      = 6 keywords per day, all 15 done in 3 days
    """
    clients       = load_clients()
    if max_clients:
        clients = clients[:max_clients]
    transport_map = get_adb_transport_map()
    devices       = list(DEVICE_POOL.keys())

    if not devices:
        print("No devices in pool. Run: python setup_devices.py --assign")
        return []

    # For each client, find their next pending keyword (not done today)
    client_pending = []
    for client in clients:
        kw_list = [kw["keyword"] if isinstance(kw, dict) else kw for kw in client["keywords"]]
        pending = [kw for kw in kw_list
                   if not is_keyword_done_today(client["id"], kw)]
        if pending:
            client_pending.append((client, pending))

    if not client_pending:
        return []

    # Track which (device, client) pairs are claimed in this planning round
    device_clients_claimed = {d: set() for d in devices}
    sessions = []

    # Round-robin: cycle through devices, assign 1 client+keyword per slot
    # Keep going until no more assignments possible
    device_idx = 0
    changed    = True
    while changed:
        changed = False
        for client, pending_kws in client_pending:
            if not pending_kws:
                continue

            # Find next device that hasn't done this client today
            for attempt in range(len(devices)):
                did = devices[(device_idx + attempt) % len(devices)]

                # Skip if this device already claimed this client
                if client["id"] in device_clients_claimed[did]:
                    continue

                # Skip if this device already did this client earlier today
                if has_device_done_client_today(did, client["id"]):
                    continue

                # Assign first pending keyword to this device
                keyword      = pending_kws.pop(0)
                dev_info     = DEVICE_POOL[did]
                short_serial = dev_info["serial"]
                port         = dev_info.get("port", BASE_APPIUM_PORT + list(DEVICE_POOL.keys()).index(did))
                full_serial  = resolve_serial(short_serial, transport_map)
                platform     = random.choice(PLATFORMS)

                # Look up backlinks for this keyword
                backlinks = []
                for kw in client["keywords"]:
                    if isinstance(kw, dict) and kw["keyword"] == keyword:
                        backlinks = kw.get("backlinks", [])
                        break

                sessions.append({
                    "client":      client,
                    "keyword":     keyword,
                    "platform":    platform,
                    "platforms":   list(PLATFORMS),
                    "device_id":   did,
                    "serial":      short_serial,
                    "full_serial": full_serial,
                    "port":        port,
                    "use_adb":     dev_info.get("use_adb", False),
                    "backlinks":   backlinks,
                    "proxy":       client.get("proxy"),
                })

                device_clients_claimed[did].add(client["id"])
                device_idx = (device_idx + attempt + 1) % len(devices)
                changed = True
                break

    return sessions


# ── Main Commands ─────────────────────────────────────────────────────────────

TEST_PROMPT = (
    "I heard {biz_name} in {city} near the downtown area is really solid "
    "for {keyword} -- do they have good reviews or any recent updates?"
)
TEST_FOLLOW_UP = (
    "Cool, do they post updates or photos on their profile so I can check them out?"
)


def run_daily(max_clients=None, test_mode=False):
    """Generate prompts, distribute to devices, run all in parallel."""
    sessions = plan_sessions(max_clients=max_clients)

    if not sessions:
        print("Nothing to run — all keywords done today or no devices available.")
        return

    print(f"\nAEO Appium Daily Session — {date.today()}")
    print(f"Devices: {len(DEVICE_POOL)} | Sessions planned: {len(sessions)}")
    if test_mode:
        print("Mode: TEST (hardcoded prompts, no LLM)")
    print("=" * 70)

    # Step 1: Generate or assign prompts
    if test_mode:
        print("\nUsing test prompts (no LLM)...")
        for sess in sessions:
            sess["prompt"] = TEST_PROMPT.format(
                biz_name=sess["client"]["biz_name"],
                city=sess["client"]["city"],
                keyword=sess["keyword"],
            )
            sess["follow_up"] = TEST_FOLLOW_UP
            print(f"  {sess['client']['biz_name']} | {sess['keyword'][:40]}")
    else:
        print("\nGenerating prompts via DeepSeek...")
        for sess in sessions:
            prompt, follow_up  = generate_session_prompts(sess["client"], sess["keyword"])
            sess["prompt"]     = prompt
            sess["follow_up"]  = follow_up
            print(f"  {sess['client']['biz_name']} | {sess['keyword'][:40]}")
            print(f"    Prompt: {prompt[:80]}...")
            if follow_up:
                print(f"    Follow-up: {follow_up[:60]}...")

    # Step 2: Mark all devices used in rotation before threads start
    for sess in sessions:
        mark_device_used(sess["device_id"], sess["client"]["id"],
                         sess["keyword"], sess["platform"])

    # Step 3: Print session plan
    print(f"\n{'='*90}")
    print(f"{'#':<3} {'Client':<25} {'Keyword':<28} {'Device':<12} {'Platforms':<14} {'Proxy'}")
    print(f"{'-'*3} {'-'*25} {'-'*28} {'-'*12} {'-'*14} {'-'*8}")
    for i, s in enumerate(sessions):
        plats = ",".join(s.get("platforms", [s["platform"]]))
        proxy_zip = s.get("proxy", {}).get("zip", "N/A") if s.get("proxy") else "OFF"
        print(f"{i+1:<3} {s['client']['biz_name']:<25} {s['keyword'][:28]:<28} "
              f"{s['device_id']:<12} {plats:<14} {proxy_zip}")
    print(f"{'='*90}")

    # Step 4: Launch all in parallel
    print(f"\nLaunching {len(sessions)} sessions in parallel...")

    def on_complete(sess, result):
        status = "success" if result.get("success") else "error"
        proxy_info = result.get("proxy")
        platform_results = result.get("platform_results", [])
        update_status(sess["device_id"], sess["client"]["id"], sess["keyword"], status)

        log_session(
            client=sess["client"],
            keyword=sess["keyword"],
            prompt=sess["prompt"],
            follow_up=sess.get("follow_up"),
            device_id=sess["device_id"],
            status=status,
            proxy_info=proxy_info,
            platform_results=platform_results,
        )

        passed = sum(1 for r in platform_results if r.get("success"))
        total = len(platform_results) or 1
        print(f"Logged: {sess['client']['biz_name']} | {sess['keyword'][:30]} | {passed}/{total} platforms | {status}")

    results       = run_parallel(sessions, on_complete=on_complete)
    success_count = sum(1 for r in results if r.get("success"))
    print(f"\nDone: {success_count}/{len(results)} sessions succeeded")
    print(f"Logs: {LOG_FILE}")


def run_audit():
    """Run weekly ranking audit for all clients x keywords."""
    clients       = load_clients()
    free_devices  = get_free_devices()
    transport_map = get_adb_transport_map()

    if not free_devices:
        print("No free devices for audit today.")
        return

    print(f"\nWeekly Ranking Audit — {date.today()}")

    sessions    = []
    device_iter = iter(free_devices)

    for client in clients:
        kw_list = [kw["keyword"] if isinstance(kw, dict) else kw for kw in client["keywords"]]
        for keyword in kw_list:
            if is_keyword_done_today(client["id"], keyword):
                continue
            try:
                device_id = next(device_iter)
            except StopIteration:
                break

            dev_info     = DEVICE_POOL[device_id]
            short_serial = dev_info["serial"]
            port         = dev_info.get("port", BASE_APPIUM_PORT)
            full_serial  = resolve_serial(short_serial, transport_map)
            platform     = random.choice(PLATFORMS)
            prompt       = generate_ranking_prompt(client, keyword)

            sessions.append({
                "client":      client,
                "keyword":     keyword,
                "platform":    platform,
                "device_id":   device_id,
                "serial":      short_serial,
                "full_serial": full_serial,
                "port":        port,
                "prompt":      prompt,
                "follow_up":   None,
            })
            mark_device_used(device_id, client["id"], keyword, platform)

    if not sessions:
        print("Nothing to audit.")
        return

    print(f"Audit sessions: {len(sessions)}")

    def on_complete(sess, result):
        status = "success" if result.get("success") else "error"
        update_status(sess["device_id"], sess["client"]["id"], sess["keyword"], status)
        log_session(sess["client"], sess["keyword"], sess["platform"],
                    sess["prompt"], None, sess["device_id"], status)
        print(f"Logged: {sess['client']['biz_name']} | {sess['keyword'][:30]} | {status}")

    results       = run_parallel(sessions, on_complete=on_complete)
    success_count = sum(1 for r in results if r.get("success"))
    print(f"\nAudit done: {success_count}/{len(results)} succeeded")


def show_status():
    """Show today's device and keyword status."""
    clients   = load_clients()
    today_rot = get_today_rotation()

    print(f"\nStatus — {date.today()}")
    print(f"Devices in pool: {len(DEVICE_POOL)}")
    print("=" * 70)

    for device_id, dev_info in DEVICE_POOL.items():
        sessions    = today_rot.get(device_id, {})
        port        = dev_info.get("port", "?")
        state       = "FREE" if not sessions else "DONE"
        print(f"\n[{state}] {device_id} ({dev_info['serial'][:24]}) port:{port}")
        for rot_key, info in sessions.items():
            print(f"   {info.get('keyword', rot_key)} | {info.get('platform')} | {info.get('status')}")

    print(f"\nClients:")
    for c in clients:
        done      = []
        for d in DEVICE_POOL:
            for rot_key in today_rot.get(d, {}):
                if rot_key.startswith(f"{c['id']}:"):
                    done.append(rot_key.split(":", 1)[1])
        kw_strs = [kw["keyword"] if isinstance(kw, dict) else kw for kw in c["keywords"]]
        remaining = [k for k in kw_strs if k not in done]
        print(f"  {c['biz_name']}: {len(done)} done, {len(remaining)} remaining")


def reset_rotation():
    """Reset today's rotation for testing."""
    today = str(date.today())
    save_rotation({today: {d: {} for d in DEVICE_POOL}})
    print(f"Rotation reset for {today}")


# ── Entry Point ───────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="AEO Appium Orchestrator v1.0")
    parser.add_argument("--audit",    action="store_true", help="Run weekly ranking audit")
    parser.add_argument("--status",   action="store_true", help="Show today's status")
    parser.add_argument("--reset",    action="store_true", help="Reset today's rotation")
    parser.add_argument("--dry-run",  action="store_true", help="Show plan without running")
    parser.add_argument("--clients",  type=int, default=None,
                        help="Limit to first N clients (for testing)")
    parser.add_argument("--exclude",  type=str, default=None,
                        help="Exclude devices by label, comma-separated (e.g. --exclude device-002,device-005)")
    parser.add_argument("--test",     action="store_true",
                        help="Use hardcoded test prompts (no LLM calls)")
    args = parser.parse_args()

    # Remove excluded devices from pool
    if args.exclude:
        excluded = [d.strip() for d in args.exclude.split(",")]
        for d in excluded:
            if d in DEVICE_POOL:
                del DEVICE_POOL[d]
                print(f"Excluded {d} from pool")
        print(f"Active devices: {len(DEVICE_POOL)}")

    if not args.status and not args.reset and not args.dry_run and not args.test:
        if not os.environ.get("DEEPSEEK_API_KEY"):
            print("DEEPSEEK_API_KEY not set!")
            print("  export DEEPSEEK_API_KEY='your-key-here'")
            sys.exit(1)

    if args.status:
        show_status()
    elif args.reset:
        reset_rotation()
    elif args.audit:
        run_audit()
    elif args.dry_run:
        sessions = plan_sessions(max_clients=args.clients)
        if not sessions:
            print("Nothing to run — all keywords done today.")
            return
        print(f"\nDRY RUN — {date.today()}")
        print(f"Devices: {len(DEVICE_POOL)} | Sessions: {len(sessions)}")
        print(f"{'='*90}")
        print(f"{'#':<3} {'Client':<25} {'Keyword':<28} {'Device':<12} {'Platforms':<14} {'Proxy'}")
        print(f"{'-'*3} {'-'*25} {'-'*28} {'-'*12} {'-'*14} {'-'*8}")
        for i, s in enumerate(sessions):
            plats = ",".join(s.get("platforms", [s["platform"]]))
            proxy_zip = s.get("proxy", {}).get("zip", "N/A") if s.get("proxy") else "OFF"
            print(f"{i+1:<3} {s['client']['biz_name']:<25} {s['keyword'][:28]:<28} "
                  f"{s['device_id']:<12} {plats:<14} {proxy_zip}")
        print(f"{'='*90}")
    else:
        run_daily(max_clients=args.clients, test_mode=args.test)


if __name__ == "__main__":
    main()
