#!/bin/bash
# start_appium.sh — Start one Appium server per device.
# Reads ports from active_devices.json (generated by: python setup_devices.py --assign).
# Falls back to discovering from adb devices with sequential ports starting at 4723.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ACTIVE_FILE="$SCRIPT_DIR/active_devices.json"
LOG_DIR="/tmp"
BASE_PORT=4723

# Always discover from adb devices — start Appium for ALL connected devices.
# active_devices.json is for the server (which devices to USE), not for Appium startup.
PAIRS=$(python3 - <<'PYEOF'
import subprocess

BASE_PORT = 4723
result = subprocess.run(["adb", "devices"], capture_output=True, text=True, timeout=10)
transports = []
for line in result.stdout.splitlines()[1:]:
    parts = line.strip().split()
    if len(parts) >= 2 and parts[1] == "device":
        transports.append(parts[0])
for idx, t in enumerate(sorted(transports)):
    label = f"device-{idx+1:03d}"
    port  = BASE_PORT + idx
    print(f"{label}:{port}")
PYEOF
)

if [[ -z "$PAIRS" ]]; then
    echo "No devices found. Connect devices or run: python setup_devices.py --assign"
    exit 1
fi

echo ""
echo "Starting Appium servers..."
echo "=================================================="

while IFS=: read -r device_id port; do
    log_file="$LOG_DIR/appium-${device_id}.log"

    # Kill any existing process on this port
    existing_pid=$(lsof -ti tcp:"$port" 2>/dev/null)
    if [[ -n "$existing_pid" ]]; then
        echo "Stopping existing process on port $port (PID $existing_pid)..."
        kill -9 "$existing_pid" 2>/dev/null
        sleep 0.3
    fi

    appium \
        --port "$port" \
        --base-path "/wd/hub" \
        --log-level "error" \
        --allow-insecure "uiautomator2:chromedriver_autodownload" \
        > "$log_file" 2>&1 &

    echo "  $device_id  port:$port  log:$log_file  PID:$!"
done <<< "$PAIRS"

echo "=================================================="
echo ""
echo "Waiting 3s for servers to initialize..."
sleep 3

echo ""
echo "Health check:"
while IFS=: read -r device_id port; do
    status=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:$port/wd/hub/status" 2>/dev/null)
    if [[ "$status" == "200" ]]; then
        echo "  $device_id  port:$port  UP"
    else
        echo "  $device_id  port:$port  DOWN (HTTP $status)"
    fi
done <<< "$PAIRS"

echo ""
echo "Done. Run 'python setup_devices.py --assign' to verify full device health."
echo ""
